Bùi Duy Thảo/TestUngDung/Areas/Admin/Controllers/OrderController.cs
using ModelEF.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class OrderController : BaseController
    {
        // GET: Admin/Order
        public ActionResult Index()
        {
            var order = new OrderDao();
            var model = order.ListAll();
            return View(model);
        }
        public ActionResult Update(System.Int32 id)
        {
            var order = new OrderDao();
            int result = order.Update(id);
            if (result == 1)
            {
                SetAlert("Duyệt đơn hàng thành công", "success");
                return RedirectToAction("Index", "Order");
            }
            else
            {
                SetAlert("Duyệt đơn hàng thất bại", "error");
            }
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(System.Int32 id)
        {
            var order = new OrderDao();
            Boolean result = order.Delete(id);
            if (result)
            {
                SetAlert("Đã xóa thành công", "success");
                return RedirectToAction("Index", "Order");
            }
            else
            {
                SetAlert("Xóa không thành công ", "error");
                return RedirectToAction("Index", "Order");
            }

        }
        public ActionResult Delete_Link(System.Int32 id)
        {
            var order = new OrderDao();
            Boolean result = order.Delete(id);
            if (result)
            {
                SetAlert("Đã xóa thành công", "success");
                return RedirectToAction("Index", "Order");
            }
            else
            {
                SetAlert("Xóa không thành công ", "error");
                return RedirectToAction("Index", "Order");
            }

        }
    }
}

Bùi Duy Thảo/TestUngDung/Areas/Admin/Controllers/OrderDetailController.cs
using ModelEF.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class OrderDetailController : Controller
    {
        // GET: Admin/OrderDetail
        public ActionResult Index(System.Int32 id)
        {
            var orderDet = new OrderDetailDao();
            var model = orderDet.ListAll(id);
            var order = new OrderDao();
            var model_only = order.FindId(id);
            ViewBag.Order = model_only;
            return View(model);
        }
    }
}

Bùi Duy Thảo/TestUngDung/Areas/Admin/Views/Order/Index.cshtml
@model IEnumerable<ModelEF.ViewModelClone.OrderModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section title{
    Order
}
<div class="card mb-4">
    <div class="card-body">
        <div class="d-flex align-items-center justify-content-around">
            <h5>Quản lí đơn hàng</h5>
        </div>
    </div>
</div>

</table>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Danh sách đơn hàng
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Tên khách hàng</th>
                        <th>Địa chỉ</th>
                        <th>Tổng tiền</th>
                        <th>Ngày tạo</th>
                        <th>Trạng thái</th>
                        <th>Chú ý</th>
                        <th>Hành động</th>
                    </tr>
                </thead>
                <tbody>
                    @{ var i = 1;}
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.OrdID">
                            <td>@i</td>
                            <td>
                                @item.CusName
                            </td>
                            <td>
                                @item.CusAddress
                            </td>
                            <td>
                                @item.OrdTotal VNĐ
                            </td>
                            <td>
                                @item.OrdDate
                            </td>
                            <td>
                                @if (@item.OrdStatus == "0")
                                {
                                    <p>Chưa duyệt</p>
                                }
                                else
                                {
                                    <p>Đã duyệt</p>
                                }

                            </td>
                            <td>
                                @item.OrdDescription
                            </td>
                            <td>
                                <a href=@Url.Action("Index", "OrderDetail", new { id = @item.OrdID }) class="btn btn-info">Chi tiết</a>
                                &nbsp;
                                @Ajax.ActionLink("Xóa ", "Delete", new { @id = item.OrdID }, new AjaxOptions
                                {
                                    Confirm = "Bạn có chắc chắn muốn xóa không ???",
                                    OnComplete = "$('#row_" + @item.OrdID + "').remove()",
                                    HttpMethod = "Delete"
                                }, new { @class = "glyphicon glyphicon-trash btn btn-danger" })
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>